jobs: 10
cluster: "sbatch -t {resources.time_min} --mem={resources.mem_mb} -c {resources.cpus} -o logs_slurm/{rule}_{wildcards} -e logs_slurm/{rule}_{wildcards} --mail-type=FAIL,BEGIN,END --mail-user=omnachmani@gmail.com"
default-resources: [cpus=2, mem_mb=2000, time_min=15]
